In [42]:
import numpy as np 



In [43]:
array1 = np.array([1,2,3])
print(type(array1))
print(type(array1.shape))

array2 = np.array([[1,2,3],[4,5,6]])
print(type(array2))
print(array2.shape)

array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [44]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)




1
2
2


In [45]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1.dtype)







<class 'list'>
<class 'numpy.ndarray'>
int64


In [46]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [47]:
array_int = np.array([1,2,3])
array_float = array_int.astype(np.float64)
print(array_float, array_float.dtype)

array_int1 = array_float.astype(np.int32)
print(array_int1, array_int1.dtype)


[1. 2. 3.] float64
[1 2 3] int32


In [48]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [49]:
zero_arr = np.zeros((3, 2), dtype=np.int32)
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

one_arr = np.ones((3, 2)) 
print(one_arr)
print(one_arr.dtype, one_arr.shape)



[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [50]:
arr1 = np.arange(10)
print(arr1)

arr2 = arr1.reshape(2, 5)
print(arr2)

arr3 = arr1.reshape(5, 2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [51]:
arr1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
arr1 = np.arange(10)
print(arr1)

arr2 = arr1.reshape(-1, 5)
print(arr2.shape)

arr3 = arr1.reshape(5, -1)
print(arr3.shape)

[0 1 2 3 4 5 6 7 8 9]
(2, 5)
(5, 2)


In [ ]:
arr1 = np.arange(10)
arr4 = arr1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
arr1 = np.arange(8)
arr3d = arr1.reshape((2,2,2))
print(arr3d.tolist())

arr5 = arr3d.reshape(-1, 1)
print(arr5.tolist())
print(arr5.shape)

arr6 = arr1.reshape(-1, 1)
print(arr6.tolist())
print(arr6.shape)

NameError: name 'np' is not defined

In [52]:
arr1 = np.arange(start=1, stop=10)
print(arr1)

value = arr1[2]
print(value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int64'>


In [53]:
print(arr1[-1])
print(arr1[-2])

9
8


In [57]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3,3)
print(arr2d)

print(arr2d[0,0])
print(arr2d[0][0])

print(arr2d[2][1])
print(arr2d[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
1
8
8


In [58]:
arr1 = np.arange(start=1, stop=10)
arr3 = arr1[0:3]
print(arr3)
print(type(arr3))

[1 2 3]
<class 'numpy.ndarray'>


In [63]:
arr2d = arr1d.reshape(3,3)
list2d = arr2d.tolist()
print(arr2d)

print(arr2d[0:2, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [64]:
print(arr2d[0].shape)
print(arr2d[1].shape)

(3,)
(3,)


In [65]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3,3)

arr3 = arr2d[[0,1], 2] 
print(arr3.tolist())

arr4 = arr2d[[0,1], 0:2]
print(arr4.tolist())

arr5 = arr2d[[0,1]]
print(arr5.tolist())



[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [67]:
arr1d = np.arange(start=1, stop=10)

arr3 = arr1d[arr1d > 5] 
print(arr3)

list1d = arr1d.tolist()
list3 = [x for x in list1d if x > 5] 
print(list3)


[6 7 8 9]
[6, 7, 8, 9]


In [ ]:
arr1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [69]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = arr1d[boolean_indexes]
print(array3)


[6 7 8 9]


In [70]:
indexes = np.array([5, 6, 7,8])
arr4 = arr1d[indexes]
print(arr4)

[6 7 8 9]


In [71]:
org_arr = np.array([3, 1 , 9 ,5])
print(org_arr)

sort_arr1 = np.sort(org_arr)
print(sort_arr1)
print(org_arr)

sort_arr2 = org_arr.sort()
print(sort_arr2)
print(org_arr)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [72]:
arr2d = np.array([[8,12], [7,1]])

sort_arr2d_axis0 = np.sort(arr2d, axis=0)
print(sort_arr2d_axis0)

sort_arr2d_axis1 = np.sort(arr2d, axis=1)
print(sort_arr2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [73]:
org_arr = np.array([3, 1 , 9 ,5])
sort_indices = np.argsort(org_arr)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [74]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [75]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8], [9,10], [11,12]])

dot_product = np.dot(A, B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [76]:
A = np.array([[1,2,3], [4,5,6]])
transpose_mat = np.transpose(A)

print(transpose_mat)

[[1 4]
 [2 5]
 [3 6]]
