In [1]:
import numpy as np 



In [2]:
array1 = np.array([1,2,3])
print(type(array1))
print(type(array1.shape))

array2 = np.array([[1,2,3],[4,5,6]])
print(type(array2))
print(array2.shape)

array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [ ]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)




1
2
2


In [5]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1.dtype)







<class 'list'>
<class 'numpy.ndarray'>
int64


In [6]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype(np.float64)
print(array_float, array_float.dtype)

array_int1 = array_float.astype(np.int32)
print(array_int1, array_int1.dtype)


[1. 2. 3.] float64
[1 2 3] int32


In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
zero_arr = np.zeros((3, 2), dtype=np.int32)
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

one_arr = np.ones((3, 2)) 
print(one_arr)
print(one_arr.dtype, one_arr.shape)



[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
arr1 = np.arange(10)
print(arr1)

arr2 = arr1.reshape(2, 5)
print(arr2)

arr3 = arr1.reshape(5, 2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
arr1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [12]:
arr1 = np.arange(10)
print(arr1)

arr2 = arr1.reshape(-1, 5)
print(arr2.shape)

arr3 = arr1.reshape(5, -1)
print(arr3.shape)

[0 1 2 3 4 5 6 7 8 9]
(2, 5)
(5, 2)


In [13]:
arr1 = np.arange(10)
arr4 = arr1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [16]:
arr1 = np.arange(8)
arr3d = arr1.reshape((2,2,2))
print(arr3d.tolist())

arr5 = arr3d.reshape(-1, 1)
print(arr5.tolist())
print(arr5.shape)

arr6 = arr1.reshape(-1, 1)
print(arr6.tolist())
print(arr6.shape)

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
